'use strict';

/**
 * #31 — the tracker is generated from the detector, not hand-maintained.
 *
 * The rendering is pure and takes plain objects, so these run without a vault
 * (the `pi-health.assess()` / `cadenceState()` split). What they pin is mostly
 * about what the generator must NOT do: invent facts it has not checked,
 * destroy Nick's editorial, or write an empty table when the read failed.
 */

const test = require('node:test');
const assert = require('node:assert');

const tracker = require('./one-to-one-tracker');

const TODAY = '2026-08-17';

function p(name, over = {}) {
  return {
    name, group: '2nd Line Technical Support', role: 'Support Analyst',
    cadence: 'fortnightly', status: 'Active',
    last121: '', next121Due: '', booked121: '', ...over,
  };
}

test('the table renders one row per person, worst first', () => {
  const out = tracker.buildTable([
    p('Calm Person', { next121Due: '2026-09-30' }),
    p('Very Late', { next121Due: '2026-06-01' }),
    p('Slightly Late', { next121Due: '2026-08-10' }),
  ], TODAY);

  const order = out.split('\n').filter(l => l.startsWith('| [[People/'));
  assert.equal(order.length, 3);
  assert.match(order[0], /Very Late/, 'longest overdue leads');
  assert.match(order[1], /Slightly Late/);
  assert.match(order[2], /Calm Person/);
});

test('states come from cadenceState, not from a second interpretation', () => {
  const out = tracker.buildTable([
    p('Booked Person', { booked121: '2026-08-20' }),
    p('Unwritten Person', { booked121: '2026-08-10', last121: '2026-07-01' }),
    p('Overdue Person', { next121Due: '2026-08-01' }),
    p('Soon Person', { next121Due: '2026-08-18' }),
  ], TODAY);

  assert.match(out, /Booked Person.*📅 Booked 2026-08-20/);
  // A booking whose date has passed with no note is "not written up" — NOT
  // "book one", which is what keeps a cancelled 1-2-1 visible.
  //
  // ⚠ The STATE is unchanged; the WORDS changed on 13 Sep 2026. This line used
  // to pin "✍️ Held 2026-08-10, not written up" — and the table this builds is
  // written into the vault, so that string put a claim in Nick's second brain
  // that a 1-2-1 had taken place when `cadenceState`'s own comment says nothing
  // here can know that. A test pinning the exact wording is what made the claim
  // look deliberate.
  assert.match(out, /Unwritten Person.*📅 Scheduled 2026-08-10 — no note/);
  // ⚠ And it must not assert attendance in any form, whatever it is reworded to.
  assert.ok(!/\bHeld\b|\bMet\b|\bAttended\b/i.test(out), out);
  assert.match(out, /Overdue Person.*⚠️ Overdue by 16d/);
  assert.match(out, /Soon Person.*⏳ Due in 1d/);
});

test('someone with no cadence is not given an invented due date', () => {
  // Maternity leave: `cadence: none`. The old table wrote "N/A — exclude" by
  // hand; inventing a fortnightly due date here is how a person on leave ends
  // up in the overdue nudge.
  const out = tracker.buildTable([
    p('On Leave', { cadence: 'none', status: 'Maternity leave' }),
  ], TODAY);
  assert.match(out, /On Leave.*— Maternity leave/);
  assert.ok(!/Overdue/.test(out));
});

test('columns NEURO cannot know are absent, not guessed', () => {
  const out = tracker.buildTable([p('Someone')], TODAY);
  // NEURO has no view of PeopleHR or of whether an invite was sent. Rendering
  // them as ❌ would state a fact it never checked.
  assert.ok(!/PeopleHR/i.test(out));
  assert.ok(!/Invite Sent/i.test(out));
  assert.match(out, /\| Person \| Team \| Cadence \| Last 1-2-1 \| Next Due \| State \|/);
});

test('the block says it is generated and must not be hand-edited', () => {
  const out = tracker.buildTable([p('Someone')], TODAY);
  assert.ok(out.startsWith(tracker.START));
  assert.ok(out.trimEnd().endsWith(tracker.END));
  assert.match(out, /Generated by NEURO on 2026-08-17/);
  assert.match(out, /Do not edit this table by hand/);
});

test('an empty roster renders a read-failure warning, never an empty table', () => {
  const out = tracker.buildTable([], TODAY);
  // "Nobody reports to Nick" and "the read failed" must not look the same.
  assert.match(out, /read failure, not an empty team/);
  assert.ok(!/\| Person \| Team \|/.test(out));
});

test('a pipe in a role or status cannot break the table', () => {
  const out = tracker.buildTable([p('Odd Person', { cadence: 'a|b' })], TODAY);
  const row = out.split('\n').find(l => l.startsWith('| [[People/'));
  assert.match(row, /a\\\|b/);
  assert.equal(row.split(/(?<!\\)\|/).length - 1, 7, 'six cells, so seven pipe boundaries');
});

test('the summary counts what is wrong', () => {
  const out = tracker.buildTable([
    p('A', { next121Due: '2026-06-01' }),
    p('B', { next121Due: '2026-06-01' }),
    p('C', { booked121: '2026-08-20' }),
  ], TODAY);
  assert.match(out, /3 reports — 2 overdue, 1 booked\./);
});

// ── splice ────────────────────────────────────────────────────────────────

const LEGACY = `---
type: area
---
# 1-2-1 Tracker

## Cadence Rules

| Status | Frequency |
|--------|-----------|
| Standard | Fortnightly |

---

## Tracker

| Person | Role | Last 1-2-1 |
|--------|------|------------|
| Arman Shazad | Analyst | 2026-03-26 |

---

## Open Actions

- [ ] Update PeopleHR for Willem Kruger

## Related

- [[Areas/Team Management|Team Management]]
`;

test("the first run replaces the legacy table and nothing else", () => {
  const out = tracker.spliceTable(LEGACY, tracker.buildTable([p('Zoe Rees')], TODAY));
  assert.ok(out, 'the note changed');
  // Nick's editorial survives — the whole reason this is surgical.
  assert.ok(out.includes('## Cadence Rules'));
  assert.ok(out.includes('| Standard | Fortnightly |'), 'the Cadence Rules TABLE is not the tracker table');
  assert.ok(out.includes('## Open Actions'));
  assert.ok(out.includes('Update PeopleHR for Willem Kruger'));
  assert.ok(out.includes('## Related'));
  // The stale row is gone.
  assert.ok(!out.includes('Arman Shazad'));
  assert.ok(out.includes('Zoe Rees'));
});

test('a second run replaces only between the markers', () => {
  const first = tracker.spliceTable(LEGACY, tracker.buildTable([p('Zoe Rees')], TODAY));
  const second = tracker.spliceTable(first, tracker.buildTable([p('Abdi Mohamed')], '2026-08-18'));
  assert.ok(second.includes('Abdi Mohamed'));
  assert.ok(!second.includes('Zoe Rees'));
  assert.ok(second.includes('## Open Actions'));
  assert.equal(second.split(tracker.START).length - 1, 1, 'exactly one generated block');
});

test('an unchanged run returns null so the mtime is not churned', () => {
  const table = tracker.buildTable([p('Zoe Rees')], TODAY);
  const first = tracker.spliceTable(LEGACY, table);
  // Re-splicing identical content must be a no-op: a rewritten file drags the
  // note into every "recently modified" scan for nothing (#78).
  assert.equal(tracker.spliceTable(first, table), null);
});

test('a note with no ## Tracker heading is left alone', () => {
  assert.equal(tracker.spliceTable('# Something else\n\nBody.\n', tracker.buildTable([p('A')], TODAY)), null);
});

test('CRLF source splices correctly', () => {
  const out = tracker.spliceTable(LEGACY.replace(/\n/g, '\r\n'), tracker.buildTable([p('Zoe Rees')], TODAY));
  assert.ok(out);
  assert.ok(out.includes('## Open Actions'));
  assert.ok(!out.includes('Arman Shazad'));
});

test('render refuses without a vault rather than writing', () => {
  const prev = process.env.OBSIDIAN_VAULT_PATH;
  delete process.env.OBSIDIAN_VAULT_PATH;
  try {
    const out = tracker.render({ apply: true });
    assert.equal(out.ok, false);
    assert.match(out.error, /OBSIDIAN_VAULT_PATH/);
  } finally {
    if (prev !== undefined) process.env.OBSIDIAN_VAULT_PATH = prev;
  }
});
