'use strict';

const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const Anthropic = require('@anthropic-ai/sdk');
const obsidian = require('../services/obsidian');
const nudges = require('../services/nudges');
const db = require('../db/database');

const VAULT_PATH = process.env.OBSIDIAN_VAULT_PATH || '';
const CLAUDE_MODEL = process.env.CLAUDE_MODEL || 'claude-sonnet-4-20250514';

// GET /api/journal/prompts — get tonight's 3 journal prompts, generated by Claude
router.get('/prompts', async (req, res) => {
  try {
    // Check if already journalled today
    const todayStr = obsidian.todayDateString();
    const journalPath = path.join(VAULT_PATH, 'Reflections', `${todayStr}-journal.md`);
    const alreadyDone = fs.existsSync(journalPath);

    // Build context from today's daily note
    let contextSummary = 'No daily note found for today.';
    try {
      const dailyNote = obsidian.readTodayDailyNote();
      if (dailyNote) {
        // Extract meaningful sections — wins, focus, meetings, EOD
        const lines = dailyNote.split('\n');
        const relevant = [];
        let inSection = false;
        const SECTIONS = ['Focus Today', 'Wins Today', 'EOD', 'Calendar', 'Meetings'];
        for (const line of lines) {
          if (line.startsWith('## ')) {
            inSection = SECTIONS.some(s => line.includes(s));
          }
          if (inSection && line.trim() && !line.startsWith('```')) {
            relevant.push(line);
          }
        }
        if (relevant.length > 0) {
          contextSummary = relevant.slice(0, 20).join('\n');
        }
      }
    } catch {}

    // Add Strava activity context
    let stravaContext = '';
    try {
      const stravaService = require('../services/strava');
      if (stravaService.isConfigured() && stravaService.isAuthenticated()) {
        const activityCtx = await stravaService.getActivityContext();
        if (activityCtx) {
          stravaContext = activityCtx;
          contextSummary = contextSummary === 'No daily note found for today.'
            ? stravaContext
            : contextSummary + '\n\n' + stravaContext;
        }
      }
    } catch (e) {
      console.warn('[Journal] Strava context failed:', e.message);
    }

    // Add Apple Health context (from iOS Shortcut webhook)
    try {
      const healthService = require('../services/health');
      const healthSummary = healthService.getHealthSummaryForJournal();
      if (healthSummary) {
        contextSummary = contextSummary === 'No daily note found for today.'
          ? healthSummary
          : contextSummary + '\n\n' + healthSummary;
        console.log('[Journal] Health context added:', healthSummary);
      }
    } catch (e) {
      console.warn('[Journal] Health context failed:', e.message);
    }

    // Generate prompts with Claude
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    const response = await client.messages.create({
      model: CLAUDE_MODEL,
      max_tokens: 256,
      system: `You are generating evening journal prompts for Nick Ward, Head of Technical Support at Nurtur.
He is neurodivergent, in a new senior leadership role, and uses journalling to process his day and maintain
self-awareness. Generate exactly 3 short, warm, specific journal prompts based on today's context.

Rules:
- Each prompt is a single question, max 15 words
- Questions should be specific to today where possible, using the context provided
- If Strava activity data is present, at least one prompt should reference it (energy, recovery, physical feeling)
- If Strava or Apple Health data is present, at least one prompt should reference physical state
- Apple Health data may include HRV, resting HR, sleep duration and quality
- Low HRV or poor sleep = ask about energy and recovery specifically
- Good metrics = affirm and ask what contributed to that
- If no health data at all, ask about physical energy/wellbeing in general terms
- Vary the focus: one about work/achievement, one about feelings/energy, one about learning/tomorrow
- Tone: warm, direct, non-judgemental — like a trusted friend asking
- Do not use bullet points or numbers — just the questions, one per line
- Never ask the same question twice`,
      messages: [{
        role: 'user',
        content: `Today's context:\n${contextSummary}\n\nGenerate 3 evening journal prompts for Nick.`
      }]
    });

    const text = response.content[0]?.text || '';
    const prompts = text.split('\n')
      .map(l => l.trim())
      .filter(l => l.length > 5 && l.endsWith('?'))
      .slice(0, 3);

    // Fallback prompts if Claude returns something unexpected
    const fallbacks = [
      "What was the one thing that actually mattered today?",
      "How are you feeling right now, honestly?",
      "What would you do differently tomorrow?"
    ];

    const finalPrompts = prompts.length === 3 ? prompts : fallbacks;

    res.json({
      prompts: finalPrompts,
      alreadyDone,
      date: todayStr
    });
  } catch (e) {
    console.error('[Journal] Prompts error:', e.message);
    res.json({
      prompts: [
        "What was the one thing that actually mattered today?",
        "How are you feeling right now, honestly?",
        "What would you do differently tomorrow?"
      ],
      alreadyDone: false,
      date: obsidian.todayDateString()
    });
  }
});

// POST /api/journal/save — save completed journal to vault
router.post('/save', (req, res) => {
  try {
    const { entries, date } = req.body;
    // entries: [{ prompt: '...', response: '...' }, ...]
    if (!entries || !Array.isArray(entries) || entries.length === 0) {
      return res.status(400).json({ error: 'entries array required' });
    }

    const todayStr = date || obsidian.todayDateString();
    const d = new Date();
    const timeStr = d.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

    const content = `---
type: reflection
subtype: journal
date: ${todayStr}
---
# Evening Journal — ${todayStr}

*Written at ${timeStr}*

${entries.map(e => `## ${e.prompt}\n\n${e.response}`).join('\n\n---\n\n')}
`;

    const reflectionsDir = path.join(VAULT_PATH, 'Reflections');
    if (!fs.existsSync(reflectionsDir)) fs.mkdirSync(reflectionsDir, { recursive: true });

    const journalPath = path.join(reflectionsDir, `${todayStr}-journal.md`);
    fs.writeFileSync(journalPath, content, 'utf-8');

    nudges.markJournalDone();
    console.log(`[Journal] Saved: ${journalPath}`);
    res.json({ success: true, path: journalPath });
  } catch (e) {
    console.error('[Journal] Save error:', e.message);
    res.status(500).json({ error: e.message });
  }
});

// GET /api/journal/settings — get current journal time setting
router.get('/settings', (req, res) => {
  const time = db.getState('journal_nudge_time') || '21:00';
  res.json({ nudgeTime: time });
});

// POST /api/journal/settings — update journal time
router.post('/settings', (req, res) => {
  const { nudgeTime } = req.body;
  if (!nudgeTime || !/^\d{2}:\d{2}$/.test(nudgeTime)) {
    return res.status(400).json({ error: 'nudgeTime required in HH:MM format' });
  }
  db.setState('journal_nudge_time', nudgeTime);
  res.json({ success: true, nudgeTime });
});

module.exports = router;
