'use strict';

const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const Anthropic = require('@anthropic-ai/sdk');
const obsidian = require('../services/obsidian');
const nudges = require('../services/nudges');
const db = require('../db/database');

const VAULT_PATH = process.env.OBSIDIAN_VAULT_PATH || '';
const CLAUDE_MODEL = process.env.CLAUDE_MODEL || 'claude-sonnet-4-20250514';

// GET /api/journal/prompts — get tonight's 3 journal prompts, generated by Claude
router.get('/prompts', async (req, res) => {
  try {
    // Check if already journalled today
    const todayStr = obsidian.todayDateString();
    const journalPath = path.join(VAULT_PATH, 'Reflections', `${todayStr}-journal.md`);
    const alreadyDone = fs.existsSync(journalPath);

    // Build context from today's daily note
    let contextSummary = 'No daily note found for today.';
    try {
      const dailyNote = obsidian.readTodayDailyNote();
      if (dailyNote) {
        // Extract meaningful sections — wins, focus, meetings, EOD
        const lines = dailyNote.split('\n');
        const relevant = [];
        let inSection = false;
        const SECTIONS = ['Focus Today', 'Wins Today', 'EOD', 'Calendar', 'Meetings'];
        for (const line of lines) {
          if (line.startsWith('## ')) {
            inSection = SECTIONS.some(s => line.includes(s));
          }
          if (inSection && line.trim() && !line.startsWith('```')) {
            relevant.push(line);
          }
        }
        if (relevant.length > 0) {
          contextSummary = relevant.slice(0, 20).join('\n');
        }
      }
    } catch {}

    // Add Strava activity context
    let stravaContext = '';
    try {
      const stravaService = require('../services/strava');
      if (stravaService.isConfigured() && stravaService.isAuthenticated()) {
        const activityCtx = await stravaService.getActivityContext();
        if (activityCtx) {
          stravaContext = activityCtx;
          contextSummary = contextSummary === 'No daily note found for today.'
            ? stravaContext
            : contextSummary + '\n\n' + stravaContext;
        }
      }
    } catch (e) {
      console.warn('[Journal] Strava context failed:', e.message);
    }

    // Add Apple Health context (from iOS Shortcut webhook)
    try {
      const healthService = require('../services/health');
      const healthSummary = healthService.getHealthSummaryForJournal();
      if (healthSummary) {
        contextSummary = contextSummary === 'No daily note found for today.'
          ? healthSummary
          : contextSummary + '\n\n' + healthSummary;
        console.log('[Journal] Health context added:', healthSummary);
      }
    } catch (e) {
      console.warn('[Journal] Health context failed:', e.message);
    }

    // Add OwnTracks location context
    try {
      const locationService = require('../services/location');
      if (locationService.isConfigured()) {
        const locationSummary = await locationService.getLocationSummaryForJournal();
        if (locationSummary) {
          contextSummary = contextSummary === 'No daily note found for today.'
            ? locationSummary
            : contextSummary + '\n\n' + locationSummary;
          console.log('[Journal] Location context added:', locationSummary);
        }
      }
    } catch (e) {
      console.warn('[Journal] Location context failed:', e.message);
    }

    // Generate prompts — Ollama first, Claude fallback
    let finalPrompts = null;
    const fallbacks = [
      "What was the one thing that actually mattered today?",
      "How are you feeling right now, honestly?",
      "What would you do differently tomorrow?"
    ];

    const journalPromptText = `Generate exactly 3 evening journal prompts for Nick Ward, Head of Technical Support at Nurtur. He is neurodivergent and uses journalling to process his day.

Rules:
- Each prompt is a single question, max 15 words
- Be specific to today's context where possible
- If Strava/health data present, reference physical state in one prompt
- If location data present showing somewhere unusual, ask about it
- Vary focus: one work/achievement, one feelings/energy, one learning/tomorrow
- Tone: warm, direct, non-judgemental
- Output ONLY the 3 questions, one per line, nothing else

Today's context:
${contextSummary}`;

    // Try Ollama first
    try {
      const ollamaRes = await fetch(`${process.env.OLLAMA_URL || 'http://localhost:11434'}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: process.env.OLLAMA_MODEL || 'qwen2.5:3b',
          prompt: journalPromptText,
          stream: false,
          options: { temperature: 0.7, num_ctx: 2048, num_predict: 200 }
        }),
        signal: AbortSignal.timeout(30000)
      });

      if (ollamaRes.ok) {
        const data = await ollamaRes.json();
        const text = data.response || '';
        const prompts = text.split('\n')
          .map(l => l.replace(/^\d+[\.\)]\s*/, '').trim())
          .filter(l => l.length > 5 && l.endsWith('?'))
          .slice(0, 3);
        if (prompts.length === 3) {
          finalPrompts = prompts;
          console.log('[Journal] Prompts generated via Ollama');
        }
      }
    } catch (ollamaErr) {
      console.warn('[Journal] Ollama failed, falling back to Claude:', ollamaErr.message);
    }

    // Claude fallback
    if (!finalPrompts) {
      try {
        const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
        const response = await client.messages.create({
          model: CLAUDE_MODEL,
          max_tokens: 256,
          system: `You are generating evening journal prompts for Nick Ward, Head of Technical Support at Nurtur.
He is neurodivergent, in a new senior leadership role, and uses journalling to process his day.
Generate exactly 3 short, warm, specific journal prompts based on today's context.
Rules: each prompt is a single question max 15 words. Vary focus: work, feelings, tomorrow. One per line.`,
          messages: [{ role: 'user', content: `Today's context:\n${contextSummary}\n\nGenerate 3 evening journal prompts for Nick.` }]
        });
        const text = response.content[0]?.text || '';
        const prompts = text.split('\n')
          .map(l => l.trim())
          .filter(l => l.length > 5 && l.endsWith('?'))
          .slice(0, 3);
        if (prompts.length === 3) finalPrompts = prompts;
        console.log('[Journal] Prompts generated via Claude (fallback)');
      } catch (claudeErr) {
        console.warn('[Journal] Claude also failed:', claudeErr.message);
      }
    }

    res.json({
      prompts: finalPrompts || fallbacks,
      alreadyDone,
      date: todayStr
    });
  } catch (e) {
    console.error('[Journal] Prompts error:', e.message);
    res.json({
      prompts: [
        "What was the one thing that actually mattered today?",
        "How are you feeling right now, honestly?",
        "What would you do differently tomorrow?"
      ],
      alreadyDone: false,
      date: obsidian.todayDateString()
    });
  }
});

// POST /api/journal/save — save completed journal to vault
router.post('/save', (req, res) => {
  try {
    const { entries, date } = req.body;
    // entries: [{ prompt: '...', response: '...' }, ...]
    if (!entries || !Array.isArray(entries) || entries.length === 0) {
      return res.status(400).json({ error: 'entries array required' });
    }

    const todayStr = date || obsidian.todayDateString();
    const d = new Date();
    const timeStr = d.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

    const content = `---
type: reflection
subtype: journal
date: ${todayStr}
---
# Evening Journal — ${todayStr}

*Written at ${timeStr}*

${entries.map(e => `## ${e.prompt}\n\n${e.response}`).join('\n\n---\n\n')}
`;

    const reflectionsDir = path.join(VAULT_PATH, 'Reflections');
    if (!fs.existsSync(reflectionsDir)) fs.mkdirSync(reflectionsDir, { recursive: true });

    const journalPath = path.join(reflectionsDir, `${todayStr}-journal.md`);
    fs.writeFileSync(journalPath, content, 'utf-8');

    nudges.markJournalDone();
    console.log(`[Journal] Saved: ${journalPath}`);
    res.json({ success: true, path: journalPath });
  } catch (e) {
    console.error('[Journal] Save error:', e.message);
    res.status(500).json({ error: e.message });
  }
});

// GET /api/journal/settings — get current journal time setting
router.get('/settings', (req, res) => {
  const time = db.getState('journal_nudge_time') || '21:00';
  res.json({ nudgeTime: time });
});

// POST /api/journal/settings — update journal time
router.post('/settings', (req, res) => {
  const { nudgeTime } = req.body;
  if (!nudgeTime || !/^\d{2}:\d{2}$/.test(nudgeTime)) {
    return res.status(400).json({ error: 'nudgeTime required in HH:MM format' });
  }
  db.setState('journal_nudge_time', nudgeTime);
  res.json({ success: true, nudgeTime });
});

module.exports = router;
